from config import *

destinations = [
    'Restaurant',
    'Cafe',
    'Bar',
    'Hotel',
    'Market',
    'Park',
    'Gym',
    'Museum',
    'Theater',
    'Library',
    'Beach',
    'Amusement Park',
    'Zoo',
    'Aquarium',
    'Shopping Mall',
    'Cinema',
    'Stadium',
    'Concert Hall',
    'Art Gallery',
    'Nightclub',
    'Spa',
    'Casino',
    'Water Park',
    'Historical Site',
    'Winery',
    'Port',
    'Bathroom',
    'Kitchen',
    'Bedroom',
    'Office',
    'School',
    'Parking Lot',
    'Public Transportation',
    'Hospital',
    'Garden',
    'Grocery Store',
    'Pharmacy',
    'Bank',
    'Supermarket',
]
