from config import *
from root_data.emojis import *

class LanguageManager:
    def __init__(self):
        self.languages = {
            "English": {
                "language_flag": "🇺🇸",
                "language_description": "Set language to English 🗣️",
                "title": "AGENTX GAME 🕵️‍♂️",
                "game_start": "🎮 The Game has started!",
                "join_game": "✅ You have joined the game.",
                "language_set": "🌐 Language has been set to English.",
                "not_enough_players_error": f"{error_emj} Not enough players. Minimum 5 required",
                "too_many_players_error": f"{error_emj} Too many players. Maximum 15 required",
                "game_started_error": f"{error_emj} Game already started. Please wait for the next round.",
                "spy_embed_description": "🔍 A game of AGENTX, AGENTX is selected and other players try to identify them by questioning each other about a certain location.",
                "host_message": "📢 Hosted By ",
                "player_list": "📝 PLAYER LIST",
                "game_cancelled_message": "❌ Game cancelled",
                "join_game_button_message": "🔲 Join Game",
                "joined_game_200_message": "🙌 You have joined the game",
                "already_ingame_message": "ℹ️ You are already in the game",
                "already_voted_message": "🗳️ You have already voted.",
                "self_vote_message": "🚫 You cannot vote for yourself.",
                "200_vote_message": "🗳️ You voted for ",
                "vote_embed_title": "VOTE FOR AGENTX 🕵️",
                "vote_embed_description": "🔘 Click the button with the name of the person you think is AGENTX.",
                "game_starting_message": "⏳ Gather in `AgentX Queue`, Game will start automatically.",
                "user_is_spy_message": "🤫 YOU ARE AGENTX",
                "user_is_detective_message": "🔍 YOU ARE A DETECTIVE",
                "user_is_spy_description": "Your mission is to deduce the secret location by skillfully questioning the detectives without revealing your true identity. Listen carefully to their responses and analyze the clues to make an educated guess, all while trying to mislead them into trusting you.",
                "user_is_detective_description": "Your mission as a detective is to uncover the spy among you. Pay close attention to each player's responses and behavior, gathering evidence through keen observation and strategic questioning to identify the traitor disguised within your ranks.",
                "location_message": "📍 THE LOCATION IS",
                "game_timer_embed_title": "⏲️ GAME TIMER",
                "time_remaining": "Time remaining: `{minutes}` minutes and `{seconds}` seconds",
                "time_is_up_message": "⏰ Time is up! Please reveal your guesses and vote who might be AGENTX.",
                "detective_won_vote": "🎉 Detectives won! `{voted_spy}` was AGENTX.",
                "spy_won_vote": "🤫 AGENTX won! `{spy}` was AgentX.",
                "game_tie": "🤝 It's a tie between",
                "start_questioning": "🕵️ You may start questioning each other.",
                "timeout_error": "⏲️ Timeout, not enough players.",
                "time_remaining2": "⏲️ Time remaining",
                "invalid_duration_error_min": f"{error_emj} Invalid duration. Minimum duration is 5 minutes.",
                "invalid_duration_error_max": f"{error_emj} Invalid duration. Maximum duration is 30 minutes.",
                "no_active_game_error" : f"{error_emj} No active game is currently running.",
                "only_host_can_stop_error": f"{error_emj} Only host can stop the current game.",
                "game_stopped_successfully": f"{sucess_emj} Game was stopped successfully",
                "player_left_the_game": f"⚠ Player left the game",
                "player_left_the_game_desc": "has left the game voice channel. They have **10 seconds** to rejoin, or they will be removed from the game.",
                "player_returned_the_game": f"{sucess_emj} Player Returned",
                "player_returned_the_game_desc": "has rejoined the game voice channel.",
                "player_removal_during_game": f"{error_emj} Player Removed",
                "player_removal_during_game_desc": "did not rejoin the game voice channel within 10 seconds and has been removed from the game.",
                "join_phase_ended": "⏳ Join Phase Ended",
                "join_phase_ended_desc": "The join phase has ended due to inactivity. No players joined in time.",
                "vote_phase_ended": "Vote Phase Ended",
                "auto_vote_message": "The vote phase has ended. Players who did not vote have been assigned a random vote.",
                "member_left_midgame": "⚠️ Player Left the Game",
                "member_left_midgame_desc": "has left the game voice channel. They have **10 seconds** to rejoin, or they will be removed from the game.",
                "player_returned_game": "✅ Player Returned",
                "player_returned_game_desc": "has rejoined the game voice channel.",
                "player_removed_midgame": "❌ Player Removed",
                "player_removed_midgame_desc": "did not rejoin the game voice channel within 10 seconds and has been removed from the game.",
                "spy_removed_midgame": "⚠️ AgentX Removed",
                "spy_removed_midgame_desc": "has been removed from the game. The game will now end.",
                "game_started_title": "Game Started!",
                "game_started_description": "Wait for the game to end to host a new game.",
                "invite_agentX": "Invite AgentX to Your Server!",
                "invite_agentX_desc": "Click the link below to invite AgentX to your server:",
                "official_support_server": "Official Support Server",
                "official_support_server_desc": "Join the official support server for AgentX:",
                "select_language": "Select a preferred language:",
                "language_selection_error": f"{error_emj} You need to have administrator permissions to execute this command.",
                "current_time": "Current time",
                "take_turns": "Take turns and start questioning eachother!",
                "agentX_settings_title": "AgentX Configuration",
                "agentX_settings_desc": "Customize your AgentX experience using the buttons and dropdowns below.",
                "current_language_title": "🌐 **Current Language**",
                "current_language_desc": "The current language for this server is **{current_language}**.",

                "agentx_commands_title": "AgentX Commands",
                "agentx_commands_desc": "AgentX uses `slash_commands` for seamless interaction.",
                "game_commands": "Game Commands",
                "game_commands_desc": "Enhance your gaming experience with these commands:",
                "guide_command": "Get a detailed guide on how to use AgentX effectively.",
                "host_command": "Hosts a game of AGENTX",
                "hint_command": "Receive a hint to help you in your game.",
                "misc_commands": "Misc Commands",
                "misc_commands_desc": "Useful miscellaneous commands to enhance your experience:",
                "support_command": "Get support for any issues you encounter.",
                "report_command": "Report any bugs you encounter.",
                "invite_command": "Invite AgentX to another server.",
                "ping_command": "Check the bot’s latency and responsiveness.",
                "owner_commands": "Owner Commands",
                "owner_commands_desc": "Commands available only to server owners:",
                "set_language_command": "Sets AgentX's language for the server.",
                "stop_command": "Stops any current AgentX's game.",
                "report_bug_error_message": "An error occurred while reporting the bug. Please try again later.",
                "report_bug_success_message": "Thank you for your report! The support has been notified.",

                "no_active_game_error": f" {error_emj} There is no active game to use this command.",
                "only_players_can_use_hint": f" {error_emj} Only players in the game can use this command.",
                "hint_command_only_in_discussion_room": f" {error_emj} This command can only be used in the discussion room.",
                "hint_cooldown_message": "You are on cooldown! Try again in {seconds} seconds.",

                "tutorial_start": "Alright, you may start questioning eachother now.",
                "tutorial_description": "if you're out of questions, use `/hint`",

                "help": {
                    "faq1": "❓ What is AGENTX Game Bot?",
                    "faq2": "🕹️ How do I start a game?",
                    "faq3": "📝 How do players join the game?",
                    "faq4": "🔍 What happens during the game?",
                    "faq5": "🎭 What roles do players get?",
                    "faq6": "📖 How to Play (Part 1)",
                    "faq7": "📖 How to Play (Part 2)",
                    "faq8": "🗳️ How to Vote",
                    "faq9": "🏆 What if the spy guesses the location correctly?",
                    "faq10": "📢 How do I report issues or provide feedback?",
                    "what_is_bot": "AGENTX Game Bot is an interactive Discord bot designed for a fun and engaging game. Players are divided into detectives and one spy without revealing their identity. The spy must figure out the location based on clues provided by the detectives while avoiding detection.",
                    "start_game": "You can start a game by using the `/host` slash command followed by the desired number of players `(minimum 5 required)`.",
                    "join_game_help": "Once the game is started, players can join by clicking the 'Join Game' button on the game embed message. The game can start when the required number of players have joined.",
                    "during_game": "After roles are assigned, detectives will start questioning each other about common points of the secret location. The spy must blend into the conversation while trying to guess the location based on the clues from the detectives.",
                    "roles": "**🕵️ AGENTX**: AgentX must deduce the secret location based on the clues given by the detectives.\n**🔍 Detective**: Detectives must identify who the AgentX is by analyzing the spy’s questions and responses.",
                    "how_to_play_part1": "1. After starting a game, players can join by clicking the 'Join Game' button on the game embed message.\n2. The game can start when the required number of players have joined.",
                    "how_to_play_part2": "1. Each player will receive a role (Spy or Detective).\n2. Detectives will discuss their clues while the spy tries to blend in and deduce the location.\n3. Players will try to identify the spy through conversation.",
                    "how_to_vote": "1. When prompted to vote, players will click the button corresponding to the person they suspect is the spy.\n2. Each player can only vote once and cannot vote for themselves.",
                    "spy_guess_correct": "If the spy guesses the location correctly, they win the game. If the detectives successfully expose the spy before their guess, the detectives win.",
                    "report_issues": "If you encounter any issues use `/report`. having suggestions to improve the bot?, join our support server! [Support Server](https://discord.gg/6fMyHbsDWS)"
                }
            },
            "French": {
                "language_flag": "🇫🇷",
                "language_description": "Définir la langue sur le français 🗣️",
                "title": "JEU D'AGENTX 🕵️‍♂️",
                "game_start": "🎮 Le jeu a commencé!",
                "join_game": "✅ Vous avez rejoint le jeu.",
                "language_set": "🌐 La langue a été définie sur le français.",
                "not_enough_players_error": f"{error_emj} Pas assez de joueurs. Minimum 5 requis",
                "too_many_players_error": f"{error_emj} Trop de joueurs. Maximum 15 requis",
                "game_started_error": "🚫 Jeu déjà commencé. Veuillez attendre le prochain tour.",
                "spy_embed_description": "🔍 Un jeu d'AgentX, un AgentX est sélectionné et les autres joueurs essaient de l'identifier en se posant des questions sur un certain lieu.",
                "host_message": "📢 Hébergé par ",
                "player_list": "📝 LISTE DES JOUEURS",
                "game_cancelled_message": "❌ Jeu annulé",
                "join_game_button_message": "🔲 Rejoindre le jeu",
                "joined_game_200_message": "🙌 Vous avez rejoint le jeu",
                "already_ingame_message": "ℹ️ Vous êtes déjà dans le jeu",
                "already_voted_message": "🗳️ Vous avez déjà voté.",
                "self_vote_message": "🚫 Vous ne pouvez pas voter pour vous-même.",
                "200_vote_message": "🗳️ Vous avez voté pour ",
                "vote_embed_title": "VOTEZ POUR L'AGENTX 🕵️",
                "vote_embed_description": "🔘 Cliquez sur le bouton avec le nom de la personne que vous pensez être l'AgentX.",
                "game_starting_message": "⏳ Rassemblez-vous dans `AgentX Queue`, le jeu commencera automatiquement.",
                "user_is_spy_message": "🤫 VOUS ÊTES L'AGENTX",
                "user_is_detective_message": "🔍 VOUS ÊTES UN DÉTECTIVE",
                "user_is_spy_description": "Votre mission est de déduire l'emplacement secret en questionnant habilement les détectives sans révéler votre véritable identité. Écoutez attentivement leurs réponses et analysez les indices pour faire une déduction éclairée, tout en essayant de les induire en erreur pour qu'ils vous fassent confiance.",
                "user_is_detective_description": "Votre mission en tant que détective est de découvrir l'AgentX parmi vous. Faites attention aux réponses et comportements de chaque joueur, en recueillant des preuves grâce à une observation minutieuse et un questionnement stratégique pour identifier le traître déguisé dans vos rangs.",
                "location_message": "📍 L'EMPLACEMENT EST",
                "game_timer_embed_title": "⏲️ MINUTEUR DU JEU",
                "time_remaining": "Temps restant: `{minutes}` minutes et `{seconds}` secondes",
                "time_is_up_message": "⏰ Le temps est écoulé ! Veuillez révéler vos suppositions et voter qui pourrait être l'AgentX.",
                "detective_won_vote": "🎉 Les détectives ont gagné! `{voted_spy}` était l'AgentX.",
                "spy_won_vote": "🤫 L'AgentX a gagné! `{spy}` était l'AgentX.",
                "game_tie": "🤝 C'est une égalité entre {', '.join(candidates)}",
                "start_questioning": "🕵️ Vous pouvez commencer à vous poser des questions.",
                "timeout_error": "⏲️ Temps écoulé, pas assez de joueurs.",
                "time_remaining2": "⏲️ Temps restant",
                "invalid_duration_error_min": f"{error_emj} Durée invalide. La durée minimale est de 5 minutes.",
                "invalid_duration_error_max": f"{error_emj} Durée invalide. La durée maximale est de 30 minutes.",
                "no_active_game_error" : f"{error_emj} Aucun jeu actif n'est actuellement en cours.",
                "only_host_can_stop_error": f"{error_emj} Seul l'hôte peut arrêter le jeu en cours.",
                "game_stopped_successfully": f"{sucess_emj} Le jeu a été arrêté avec succès",
                "player_left_the_game": f"⚠ Joueur a quitté le jeu",
                "player_left_the_game_desc": "a quitté le canal vocal du jeu. Ils ont **10 secondes** pour revenir, sinon ils seront retirés du jeu.",
                "player_returned_the_game": f"{sucess_emj} Joueur Revenu",
                "player_returned_the_game_desc": "a rejoint de nouveau le canal vocal du jeu.",
                "player_removal_during_game": f"{error_emj} Joueur Supprimé",
                "player_removal_during_game_desc": "n'a pas rejoint le canal vocal du jeu dans les 10 secondes et a été retiré du jeu.",
                "join_phase_ended": "⏳ Phase de Rejoint Terminée",
                "join_phase_ended_desc": "La phase de rejoint s'est terminée en raison de l'inactivité. Aucun joueur n'a rejoint à temps.",
                "vote_phase_ended": "🗳️ Phase de Vote Terminée",
                "auto_vote_message": "La phase de vote est terminée. Les joueurs qui n'ont pas voté ont reçu un vote aléatoire. 🔄",
                "member_left_midgame": "⚠️ Joueur a quitté le jeu",
                "member_left_midgame_desc": "a quitté le canal vocal du jeu. Ils ont **10 secondes** pour revenir, sinon ils seront retirés du jeu.",
                "player_returned_game": "✅ Joueur est revenu",
                "player_returned_game_desc": "a rejoint le canal vocal du jeu.",
                "player_removed_midgame": "❌ Joueur retiré",
                "player_removed_midgame_desc": "n'est pas revenu dans le canal vocal du jeu dans les 10 secondes et a été retiré du jeu.",
                "spy_removed_midgame": "⚠️ AgentX retiré",
                "spy_removed_midgame_desc": "a été retiré du jeu. Le jeu se terminera maintenant.",
                "game_started_title": "Jeu commencé!",
                "game_started_description": "Attendez la fin du jeu pour héberger un nouveau jeu.",
                "invite_agentX": "Invitez AgentX sur votre serveur!",
                "invite_agentX_desc": "Cliquez sur le lien ci-dessous pour inviter AgentX sur votre serveur:",
                "official_support_server": "Serveur de support officiel",
                "official_support_server_desc": "Rejoignez le serveur de support officiel pour AgentX:",
                "select_language": "Sélectionnez une langue préférée:",
                "language_selection_error": f"{error_emj} Vous devez avoir les permissions d'administrateur pour exécuter cette commande.",
                "current_time": "Heure actuelle",
                "take_turns": "Prenez chacun votre tour et commencez à vous poser des questions !",
                "agentX_settings_title": "Configuration d'AgentX",
                "agentX_settings_desc": "Personnalisez votre expérience AgentX en utilisant les boutons et les menus déroulants ci-dessous.",
                "current_language_title": "🌐 **Langue actuelle**",
                "current_language_desc": "La langue actuelle de ce serveur est **{current_language}**.",

                "agentx_commands_title": "Commandes AgentX",
                "agentx_commands_desc": "AgentX utilise les `slash_commands` pour une interaction fluide.",
                "game_commands": "Commandes de Jeu",
                "game_commands_desc": "Améliorez votre expérience de jeu avec ces commandes :",
                "guide_command": "Obtenez un guide détaillé sur l'utilisation efficace d'AgentX.",
                "host_command": "Héberge une partie d'AGENTX",
                "hint_command": "Recevez un indice pour vous aider dans votre jeu.",
                "misc_commands": "Commandes Diverses",
                "misc_commands_desc": "Commandes diverses utiles pour améliorer votre expérience :",
                "support_command": "Obtenez de l'aide pour tous les problèmes rencontrés.",
                "report_command": "Signalez les bugs rencontrés.",
                "invite_command": "Invitez AgentX sur un autre serveur.",
                "ping_command": "Vérifiez la latence et la réactivité du bot.",
                "owner_commands": "Commandes Propriétaire",
                "owner_commands_desc": "Commandes disponibles uniquement pour les propriétaires du serveur :",
                "set_language_command": "Définit la langue d'AgentX pour le serveur.",
                "stop_command": "Arrête le jeu en cours d'AgentX.",
                "report_bug_error_message": "Une erreur s'est produite lors du signalement du bug. Veuillez réessayer plus tard.",
                "report_bug_success_message": "Merci pour votre signalement ! Le support a été informé.",

                "no_active_game_error": " {error_emj} Il n'y a pas de jeu actif pour utiliser cette commande.",
                "only_players_can_use_hint": " {error_emj} Seuls les joueurs du jeu peuvent utiliser cette commande.",
                "hint_command_only_in_discussion_room": " {error_emj} Cette commande ne peut être utilisée que dans la salle de discussion.",
                "hint_cooldown_message": "Vous êtes en période de cooldown ! Réessayez dans {seconds} secondes.",

                "tutorial_start": "C'est parti ! Commencez à vous poser des questions maintenant.",
                "tutorial_description": "Si vous êtes bloqué, tapez simplement `/hint` pour obtenir de l'aide.",


                "help": {
                    "faq1": "❓ Qu'est-ce que le AgentX Game Bot?",
                    "faq2": "🕹️ Comment démarrer un jeu?",
                    "faq3": "📝 Comment les joueurs rejoignent-ils le jeu?",
                    "faq4": "🔍 Que se passe-t-il pendant le jeu?",
                    "faq5": "🎭 Quels rôles les joueurs obtiennent-ils?",
                    "faq6": "📖 Comment jouer (Partie 1)",
                    "faq7": "📖 Comment jouer (Partie 2)",
                    "faq8": "🗳️ Comment voter",
                    "faq9": "🏆 Que se passe-t-il si l'AgentX devine correctement l'emplacement?",
                    "faq10": "📢 Comment signaler des problèmes ou fournir des commentaires?",
                    "what_is_bot": "Le AgentX Game Bot est un bot interactif Discord conçu pour un jeu amusant et engageant. Les joueurs sont divisés en détectives et un AgentX sans révéler leur identité. L'AgentX doit deviner l'emplacement en se basant sur les indices fournis par les détectives tout en évitant d'être détecté.",
                    "start_game": "Vous pouvez démarrer un jeu en utilisant la commande slash `/host` suivie du nombre de joueurs souhaité `(minimum 5 requis)`.",
                    "join_game_help": "Une fois le jeu commencé, les joueurs peuvent rejoindre en cliquant sur le bouton 'Rejoindre le jeu' sur le message intégré du jeu. Le jeu peut commencer lorsque le nombre requis de joueurs a rejoint.",
                    "during_game": "Après l'attribution des rôles, les détectives commenceront à se poser des questions sur des points communs de l'emplacement secret. L'AgentX doit se fondre dans la conversation tout en essayant de deviner l'emplacement en se basant sur les indices des détectives.",
                    "roles": "**🕵️ AgentX**: L'AgentX doit déduire l'emplacement secret en se basant sur les indices donnés par les détectives.\n**🔍 Détective**: Les détectives doivent identifier qui est l'AgentX en analysant les questions et réponses de l'AgentX.",
                    "how_to_play_part1": "1. Après avoir commencé un jeu, les joueurs peuvent rejoindre en cliquant sur le bouton 'Rejoindre le jeu' sur le message intégré du jeu.\n2. Le jeu peut commencer lorsque le nombre requis de joueurs a rejoint.",
                    "how_to_play_part2": "1. Chaque joueur recevra un rôle (AgentX ou Détective).\n2. Les détectives discuteront de leurs indices pendant que l'AgentX essaie de se fondre et de deviner l'emplacement.\n3. Les joueurs essaieront d'identifier l'AgentX à travers la conversation.",
                    "how_to_vote": "1. Lorsqu'on vous demande de voter, les joueurs cliqueront sur le bouton correspondant à la personne qu'ils soupçonnent d'être l'AgentX.\n2. Chaque joueur ne peut voter qu'une seule fois et ne peut pas voter pour lui-même.",
                    "spy_guess_correct": "Si l'AgentX devine correctement l'emplacement, il gagne le jeu. Si les détectives exposent avec succès l'AgentX avant sa supposition, les détectives gagnent.",
                    "report_issues": "Si vous rencontrez des problèmes, utilisez `/report`. Vous avez des suggestions pour améliorer le bot? Rejoignez notre serveur de support! [Serveur de support](https://discord.gg/6fMyHbsDWS)"
                }
            },
            "Arabic": {
                "language_flag": "🇸🇦",
                "language_description": "تعيين اللغة إلى العربية 🗣️",
                "title": "لعبة التجسس 🕵️‍♂️",
                "game_start": "🎮 بدأت اللعبة!",
                "join_game": "✅ لقد انضممت إلى اللعبة.",
                "language_set": "🌐 تم تعيين اللغة إلى العربية.",
                "not_enough_players_error": f"{error_emj} عدد اللاعبين غير كاف. الحد الأدنى 5 مطلوب",
                "too_many_players_error": f"{error_emj} عدد اللاعبين كبير جدًا. الحد الأقصى المطلوب 15",
                "game_started_error": "🚫 اللعبة بدأت بالفعل. يرجى الانتظار للجولة القادمة.",
                "spy_embed_description": "🔍 لعبة التجسس، يتم اختيار جاسوس ويحاول اللاعبون الآخرون التعرف عليه من خلال طرح الأسئلة على بعضهم البعض حول موقع معين.",
                "host_message": "📢 مستضافة من قبل ",
                "player_list": "📝 قائمة اللاعبين",
                "game_cancelled_message": "❌ تم إلغاء اللعبة",
                "join_game_button_message": "🔲 انضم إلى اللعبة",
                "joined_game_200_message": "🙌 لقد انضممت إلى اللعبة",
                "already_ingame_message": "ℹ️ أنت بالفعل في اللعبة",
                "already_voted_message": "🗳️ لقد قمت بالتصويت بالفعل.",
                "self_vote_message": "🚫 لا يمكنك التصويت لنفسك.",
                "200_vote_message": "🗳️ قمت بالتصويت لـ ",
                "vote_embed_title": "صوت للجاسوس 🕵️",
                "vote_embed_description": "🔘 انقر فوق الزر باسم الشخص الذي تعتقد أنه الجاسوس.",
                "game_starting_message": "⏳ اجتمعوا في `AgentX Queue`, ستبدأ اللعبة تلقائياً.",
                "user_is_spy_message": "🤫 أنت الجاسوس",
                "user_is_detective_message": "🔍 أنت محقق",
                "user_is_spy_description": "مهمتك هي استنتاج الموقع السري من خلال استجواب المحققين بمهارة دون كشف هويتك الحقيقية. استمع جيدًا إلى إجاباتهم وحلل الأدلة لتقديم تخمين مستنير، مع محاولة تضليلهم لجعلك تثق بهم.",
                "user_is_detective_description": "مهمتك كمحقق هي اكتشاف الجاسوس بينكم. انتبه جيدًا لإجابات وسلوك كل لاعب، واجمع الأدلة من خلال الملاحظة الدقيقة والاستجواب الاستراتيجي لتحديد الجاسوس المتخفي بين صفوفكم.",
                "location_message": "📍 الموقع هو",
                "game_timer_embed_title": "⏲️ مؤقت اللعبة",
                "time_remaining": "الوقت المتبقي: `{minutes}` دقيقة و `{seconds}` ثانية",
                "time_is_up_message": "⏰ انتهى الوقت! يرجى الكشف عن تخميناتكم والتصويت لمن قد يكون الجاسوس.",
                "detective_won_vote": "🎉 فاز المحققون! `{voted_spy}` كان الجاسوس.",
                "spy_won_vote": "🤫 فاز الجاسوس! `{spy}` كان الجاسوس.",
                "game_tie": "🤝 إنها تعادل بين {', '.join(candidates)}",
                "start_questioning": "🕵️ يمكنك بدء استجواب بعضكم البعض.",
                "timeout_error": "⏲️ انتهى الوقت، عدد اللاعبين غير كاف.",
                "time_remaining2": "⏲️ الوقت المتبقي",
                "invalid_duration_error_min": f"{error_emj} مدة غير صالحة. الحد الأدنى للمدة هو 5 دقائق.",
                "invalid_duration_error_max": f"{error_emj} مدة غير صالحة. الحد الأقصى للمدة هو 30 دقيقة.",
                "no_active_game_error" : f"{error_emj} لا يوجد لعبة نشطة حاليًا.",
                "only_host_can_stop_error": f"{error_emj} فقط المضيف يمكنه إيقاف اللعبة الحالية.",
                "game_stopped_successfully": f"{sucess_emj} تم إيقاف اللعبة بنجاح",
                "player_left_the_game": f"⚠ اللاعب غادر اللعبة",
                "player_left_the_game_desc": "غادر القناة الصوتية للعبة. لديهم **10 ثوانٍ** للعودة، أو سيتم إزالتهم من اللعبة.",
                "player_returned_the_game": f"{sucess_emj} عاد اللاعب",
                "player_returned_the_game_desc": "عاد إلى القناة الصوتية للعبة.",
                "player_removal_during_game": f"{error_emj} اللاعب مُزال",
                "player_removal_during_game_desc": "لم يعد إلى القناة الصوتية للعبة خلال 10 ثوانٍ وتمت إزالته من اللعبة.",
                "join_phase_ended": "⏳ انتهت مرحلة الانضمام",
                "join_phase_ended_desc": "انتهت مرحلة الانضمام بسبب عدم النشاط. لم ينضم أي لاعب في الوقت المناسب.",
                "vote_phase_ended": "🗳️ انتهت مرحلة التصويت",
                "auto_vote_message": "انتهت مرحلة التصويت. تم تعيين تصويت عشوائي للاعبين الذين لم يصوتوا. 🔄",
                "member_left_midgame": "⚠️ اللاعب غادر اللعبة",
                "member_left_midgame_desc": "غادر قناة الصوت الخاصة باللعبة. لديهم **10 ثواني** للعودة، أو سيتم إزالتهم من اللعبة.",
                "player_returned_game": "✅ اللاعب عاد",
                "player_returned_game_desc": "أعاد الانضمام إلى قناة الصوت الخاصة باللعبة.",
                "player_removed_midgame": "❌ اللاعب تمت إزالته",
                "player_removed_midgame_desc": "لم يعد إلى قناة الصوت الخاصة باللعبة خلال 10 ثواني وتم إزالته من اللعبة.",
                "spy_removed_midgame": "⚠️ تم إزالة AgentX",
                "spy_removed_midgame_desc": "تمت إزالته من اللعبة. ستنتهي اللعبة الآن.",
                "game_started_title": "بدأت اللعبة!",
                "game_started_description": "انتظر حتى تنتهي اللعبة لاستضافة لعبة جديدة.",
                "invite_agentX": "ادعو AgentX إلى خادمك!",
                "invite_agentX_desc": "انقر على الرابط أدناه لدعوة AgentX إلى خادمك:",
                "official_support_server": "خادم الدعم الرسمي",
                "official_support_server_desc": "انضم إلى خادم الدعم الرسمي لـ AgentX:",
                "select_language": "اختر لغة مفضلة:",
                "language_selection_error": f"{error_emj} تحتاج إلى صلاحيات المشرف لتنفيذ هذا الأمر.",
                "current_time": "الوقت الحالي",
                "take_turns": "تناوبوا وابدأوا في طرح الأسئلة على بعضكم البعض!",
                "agentX_settings_title": "إعدادات AgentX",
                "agentX_settings_desc": "قم بتخصيص تجربة AgentX الخاصة بك باستخدام الأزرار والقوائم المنسدلة أدناه.",
                "current_language_title": "🌐 **اللغة الحالية**",
                "current_language_desc": "اللغة الحالية لهذا الخادم هي **{current_language}**.",

            
                "agentx_commands_title": "أوامر AgentX",
                "agentx_commands_desc": "يستخدم AgentX الأوامر المائلة `slash_commands` لتفاعل سلس.",
                "game_commands": "أوامر اللعبة",
                "game_commands_desc": "عزز تجربتك في اللعبة بهذه الأوامر:",
                "guide_command": "احصل على دليل مفصل حول كيفية استخدام AgentX بفعالية.",
                "host_command": "يستضيف لعبة AGENTX",
                "hint_command": "تلقي تلميح لمساعدتك في اللعبة.",
                "misc_commands": "أوامر متنوعة",
                "misc_commands_desc": "أوامر متنوعة لتحسين تجربتك:",
                "support_command": "الحصول على الدعم لأي مشاكل تواجهك.",
                "report_command": "أبلغ عن أي أخطاء تواجهك.",
                "invite_command": "قم بدعوة AgentX إلى خادم آخر.",
                "ping_command": "تحقق من تأخر البوت واستجابته.",
                "owner_commands": "أوامر المالك",
                "owner_commands_desc": "الأوامر المتاحة فقط لأصحاب الخادم:",
                "set_language_command": "يحدد لغة AgentX للخادم.",
                "stop_command": "يوقف اللعبة الحالية لـ AgentX.",
                "report_bug_error_message": "حدث خطأ أثناء الإبلاغ عن المشكلة. الرجاء المحاولة مرة أخرى لاحقاً.",
                "report_bug_success_message": "شكراً لتقريرك! تم إخطار الدعم.",

                "no_active_game_error": " {error_emj} لا يوجد لعبة نشطة لاستخدام هذا الأمر.",
                "only_players_can_use_hint": " {error_emj} يمكن فقط للاعبين في اللعبة استخدام هذا الأمر.",
                "hint_command_only_in_discussion_room": " {error_emj} يمكن استخدام هذا الأمر فقط في غرفة المناقشة.",
                "hint_cooldown_message": "أنت في فترة التهدئة! حاول مرة أخرى بعد {seconds} ثانية.",

                "tutorial_start": "لنبدأ! ابدأ في طرح الأسئلة على بعضكم البعض الآن.",
                "tutorial_description": "إذا كنت عالقًا، فقط اكتب `/hint` للحصول على بعض المساعدة.",


                "help": {
                    "faq1": "❓ ما هو بوت لعبة التجسس؟",
                    "faq2": "🕹️ كيف أبدأ اللعبة؟",
                    "faq3": "📝 كيف ينضم اللاعبون إلى اللعبة؟",
                    "faq4": "🔍 ماذا يحدث خلال اللعبة؟",
                    "faq5": "🎭 ما هي الأدوار التي يحصل عليها اللاعبون؟",
                    "faq6": "📖 كيفية اللعب (الجزء 1)",
                    "faq7": "📖 كيفية اللعب (الجزء 2)",
                    "faq8": "🗳️ كيفية التصويت",
                    "faq9": "🏆 ماذا يحدث إذا خمن الجاسوس الموقع بشكل صحيح؟",
                    "faq10": "📢 كيف أبلغ عن المشاكل أو أقدم التعليقات؟",
                    "what_is_bot": "بوت لعبة التجسس هو بوت تفاعلي على ديسكورد مصمم للعبة ممتعة وجذابة. يتم تقسيم اللاعبين إلى محققين وجاسوس واحد دون الكشف عن هويتهم. يجب على الجاسوس اكتشاف الموقع بناءً على الأدلة المقدمة من المحققين أثناء تجنب اكتشافه.",
                    "start_game": "يمكنك بدء اللعبة باستخدام أمر الشرط `/host` متبوعًا بعدد اللاعبين المطلوب `(الحد الأدنى 5 مطلوب)`.",
                    "join_game_help": "بمجرد بدء اللعبة، يمكن للاعبين الانضمام بالنقر على زر 'انضم إلى اللعبة' في رسالة اللعبة المدمجة. يمكن أن تبدأ اللعبة عندما ينضم العدد المطلوب من اللاعبين.",
                    "during_game": "بعد تعيين الأدوار، سيبدأ المحققون في طرح الأسئلة على بعضهم البعض حول نقاط مشتركة في الموقع السري. يجب على الجاسوس الاندماج في المحادثة أثناء محاولته تخمين الموقع بناءً على الأدلة من المحققين.",
                    "roles": "**🕵️ الجاسوس**: يجب على الجاسوس استنتاج الموقع السري بناءً على الأدلة المقدمة من المحققين.\n**🔍 المحقق**: يجب على المحققين تحديد من هو الجاسوس من خلال تحليل أسئلته وإجاباته.",
                    "how_to_play_part1": "1. بعد بدء اللعبة، يمكن للاعبين الانضمام بالنقر على زر 'انضم إلى اللعبة' في رسالة اللعبة المدمجة.\n2. يمكن أن تبدأ اللعبة عندما ينضم العدد المطلوب من اللاعبين.",
                    "how_to_play_part2": "1. سيتلقى كل لاعب دورًا (جاسوس أو محقق).\n2. سيناقش المحققون أدلتهم بينما يحاول الجاسوس الاندماج وتخمين الموقع.\n3. سيحاول اللاعبون تحديد الجاسوس من خلال المحادثة.",
                    "how_to_vote": "1. عند مطالبتك بالتصويت، سيقوم اللاعبون بالنقر على الزر المقابل للشخص الذي يعتقدون أنه الجاسوس.\n2. يمكن لكل لاعب التصويت مرة واحدة فقط ولا يمكنه التصويت لنفسه.",
                    "spy_guess_correct": "إذا خمن الجاسوس الموقع بشكل صحيح، يفوز في اللعبة. إذا نجح المحققون في كشف الجاسوس قبل تخمينه، يفوز المحققون.",
                    "report_issues": "إذا واجهت أي مشكلات استخدم `/report`. هل لديك اقتراحات لتحسين البوت؟ انضم إلى خادم الدعم الخاص بنا! [خادم الدعم](https://discord.gg/6fMyHbsDWS)"

                }
            },
            "German": {
                "language_flag": "🇩🇪",
                "language_description": "Sprache auf Deutsch einstellen 🗣️",
                "title": "AGENTX-SPIEL 🕵️‍♂️",
                "game_start": "🎮 Das Spiel hat begonnen!",
                "join_game": "✅ Sie haben dem Spiel beigetreten.",
                "language_set": "🌐 Die Sprache wurde auf Deutsch eingestellt.",
                "not_enough_players_error": f"{error_emj} Nicht genügend Spieler. Mindestens 5 erforderlich",
                "too_many_players_error": f"{error_emj} Zu viele Spieler. Maximal 15 erlaubt",
                "game_started_error": "🚫 Das Spiel hat bereits begonnen. Bitte warten Sie auf die nächste Runde.",
                "spy_embed_description": "🔍 Ein AgentX-Spiel, ein AgentX wird ausgewählt und die anderen Spieler versuchen, ihn zu identifizieren, indem sie Fragen zu einem bestimmten Ort stellen.",
                "host_message": "📢 Gehostet von ",
                "player_list": "📝 SPIELERLISTE",
                "game_cancelled_message": "❌ Spiel abgebrochen",
                "join_game_button_message": "🔲 Spiel beitreten",
                "joined_game_200_message": "🙌 Sie haben dem Spiel beigetreten",
                "already_ingame_message": "ℹ️ Sie sind bereits im Spiel",
                "already_voted_message": "🗳️ Sie haben bereits abgestimmt.",
                "self_vote_message": "🚫 Sie können nicht für sich selbst stimmen.",
                "200_vote_message": "🗳️ Sie haben für gestimmt ",
                "vote_embed_title": "STIMMEN SIE FÜR AGENTX AB 🕵️",
                "vote_embed_description": "🔘 Klicken Sie auf den Button mit dem Namen der Person, von der Sie denken, dass sie der AgentX ist.",
                "game_starting_message": "⏳ Versammelt euch in `AgentX Queue`, das Spiel startet automatisch.",
                "user_is_spy_message": "🤫 SIE SIND DER AGENTX",
                "user_is_detective_message": "🔍 SIE SIND EIN DETEKTIV",
                "user_is_spy_description": "Ihre Mission ist es, den geheimen Standort zu erraten, indem Sie die Detektive geschickt befragen, ohne Ihre wahre Identität preiszugeben. Hören Sie aufmerksam auf ihre Antworten und analysieren Sie die Hinweise, um eine fundierte Vermutung anzustellen, während Sie versuchen, sie in die Irre zu führen, damit sie Ihnen vertrauen.",
                "user_is_detective_description": "Ihre Mission als Detektiv ist es, den AgentX unter Ihnen zu entlarven. Achten Sie auf die Antworten und das Verhalten jedes Spielers und sammeln Sie Beweise durch sorgfältige Beobachtung und strategisches Befragen, um den getarnten Verräter in Ihren Reihen zu identifizieren.",
                "location_message": "📍 DER STANDORT IST",
                "game_timer_embed_title": "⏲️ SPIELTIMER",
                "time_remaining": "Verbleibende Zeit: `{minutes}` Minuten und `{seconds}` Sekunden",
                "time_is_up_message": "⏰ Die Zeit ist abgelaufen! Bitte geben Sie Ihre Vermutungen ab und stimmen Sie darüber ab, wer der AgentX sein könnte.",
                "detective_won_vote": "🎉 Die Detektive haben gewonnen! `{voted_spy}` war der AgentX.",
                "spy_won_vote": "🤫 Der AgentX hat gewonnen! `{spy}` war der AgentX.",
                "game_tie": "🤝 Es gibt einen Gleichstand zwischen {', '.join(candidates)}",
                "start_questioning": "🕵️ Sie können beginnen, sich gegenseitig Fragen zu stellen.",
                "timeout_error": "⏲️ Zeitüberschreitung, nicht genügend Spieler.",
                "time_remaining2": "⏲️ Verbleibende Zeit",
                "invalid_duration_error_min": f"{error_emj} Ungültige Dauer. Die Mindestdauer beträgt 5 Minuten.",
                "invalid_duration_error_max": f"{error_emj} Ungültige Dauer. Die Höchstdauer beträgt 30 Minuten.",
                "no_active_game_error" : f"{error_emj} Derzeit läuft kein aktives Spiel.",
                "only_host_can_stop_error": f"{error_emj} Nur der Gastgeber kann das laufende Spiel stoppen.",
                "game_stopped_successfully": f"{sucess_emj} Das Spiel wurde erfolgreich gestoppt",
                "player_left_the_game": f"⚠ Ein Spieler hat das Spiel verlassen",
                "player_left_the_game_desc": "hat den Sprachkanal des Spiels verlassen. Sie haben **10 Sekunden** Zeit, zurückzukehren, sonst werden sie aus dem Spiel entfernt.",
                "player_returned_the_game": f"{sucess_emj} Spieler Zurückgekehrt",
                "player_returned_the_game_desc": "ist dem Sprachkanal des Spiels wieder beigetreten.",
                "player_removal_during_game": f"{error_emj} Spieler Entfernt",
                "player_removal_during_game_desc": "hat den Sprachkanal des Spiels innerhalb von 10 Sekunden nicht wieder beigetreten und wurde aus dem Spiel entfernt.",
                "join_phase_ended": "⏳ Beitrittsphase Beendet",
                "join_phase_ended_desc": "Die Beitrittsphase wurde aufgrund von Inaktivität beendet. Keine Spieler sind rechtzeitig beigetreten.",
                "vote_phase_ended": "🗳️ Abstimmungsphase Beendet",
                "auto_vote_message": "Die Abstimmungsphase ist beendet. Spieler, die nicht abgestimmt haben, wurden zufällig zugeordnet. 🔄",
                "member_left_midgame": "⚠️ Spieler hat das Spiel verlassen",
                "member_left_midgame_desc": "hat den Spiele-Voice-Channel verlassen. Sie haben **10 Sekunden**, um zurückzukehren, oder sie werden aus dem Spiel entfernt.",
                "player_returned_game": "✅ Spieler ist zurück",
                "player_returned_game_desc": "ist dem Spiele-Voice-Channel wieder beigetreten.",
                "player_removed_midgame": "❌ Spieler entfernt",
                "player_removed_midgame_desc": "ist innerhalb von 10 Sekunden nicht in den Spiele-Voice-Channel zurückgekehrt und wurde aus dem Spiel entfernt.",
                "spy_removed_midgame": "⚠️ AgentX entfernt",
                "spy_removed_midgame_desc": "wurde aus dem Spiel entfernt. Das Spiel wird jetzt enden.",
                "game_started_title": "Spiel gestartet!",
                "game_started_description": "Warten Sie auf das Ende des Spiels, um ein neues Spiel zu hosten.",
                "invite_agentX": "Laden Sie AgentX auf Ihren Server ein!",
                "invite_agentX_desc": "Klicken Sie auf den unten stehenden Link, um AgentX auf Ihren Server einzuladen:",
                "official_support_server": "Offizieller Support-Server",
                "official_support_server_desc": "Treten Sie dem offiziellen Support-Server für AgentX bei:",
                "select_language": "Wählen Sie eine bevorzugte Sprache:",
                "language_selection_error": f"{error_emj} Sie benötigen Administratorrechte, um diesen Befehl auszuführen.",
                "current_time": "Aktuelle Zeit",
                "take_turns": "Wechselt euch ab und fangt an, euch gegenseitig Fragen zu stellen!",
                "agentX_settings_title": "AgentX-Konfiguration",
                "agentX_settings_desc": "Passen Sie Ihre AgentX-Erfahrung mit den untenstehenden Schaltflächen und Dropdown-Menüs an.",
                "current_language_title": "🌐 **Aktuelle Sprache**",
                "current_language_desc": "Die aktuelle Sprache für diesen Server ist **{current_language}**.",

                "agentx_commands_title": "AgentX Befehle",
                "agentx_commands_desc": "AgentX verwendet `slash_commands` für eine nahtlose Interaktion.",
                "game_commands": "Spielbefehle",
                "game_commands_desc": "Verbessern Sie Ihr Spielerlebnis mit diesen Befehlen:",
                "guide_command": "Erhalten Sie eine detaillierte Anleitung zur effektiven Nutzung von AgentX.",
                "host_command": "Hostet ein Spiel von AGENTX",
                "hint_command": "Erhalten Sie einen Hinweis, der Ihnen im Spiel hilft.",
                "misc_commands": "Verschiedene Befehle",
                "misc_commands_desc": "Nützliche verschiedene Befehle zur Verbesserung Ihrer Erfahrung:",
                "support_command": "Erhalten Sie Unterstützung bei auftretenden Problemen.",
                "report_command": "Melden Sie aufgetretene Fehler.",
                "invite_command": "Laden Sie AgentX zu einem anderen Server ein.",
                "ping_command": "Überprüfen Sie die Latenz und Reaktionsfähigkeit des Bots.",
                "owner_commands": "Besitzerbefehle",
                "owner_commands_desc": "Befehle, die nur für Serverbesitzer verfügbar sind:",
                "set_language_command": "Setzt die Sprache für AgentX im Server.",
                "stop_command": "Stoppt das aktuelle Spiel von AgentX.",
                "report_bug_error_message": "Beim Melden des Fehlers ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.",
                "report_bug_success_message": "Vielen Dank für Ihren Bericht! Der Support wurde benachrichtigt.",

                "no_active_game_error": f"{error_emj} Es gibt kein aktives Spiel, um diesen Befehl zu verwenden.",
                "only_players_can_use_hint": f"{error_emj} Nur Spieler im Spiel können diesen Befehl verwenden.",
                "hint_command_only_in_discussion_room": f"{error_emj} Dieser Befehl kann nur im Diskussionsraum verwendet werden.",
                "hint_cooldown_message": "Du bist auf Abkühlung! Versuchen Sie es in {seconds} Sekunden erneut.",

                "tutorial_start": "Lasst uns anfangen! Beginnt jetzt, euch gegenseitig Fragen zu stellen.",
                "tutorial_description": "Wenn ihr feststeckt, tippt einfach `/hint` für Hilfe.",


                "help": {
                    "faq1": "❓ Was ist der AgentX Game Bot?",
                    "faq2": "🕹️ Wie starte ich ein Spiel?",
                    "faq3": "📝 Wie treten Spieler dem Spiel bei?",
                    "faq4": "🔍 Was passiert während des Spiels?",
                    "faq5": "🎭 Welche Rollen erhalten die Spieler?",
                    "faq6": "📖 Wie spielt man (Teil 1)",
                    "faq7": "📖 Wie spielt man (Teil 2)",
                    "faq8": "🗳️ Wie man abstimmt",
                    "faq9": "🏆 Was passiert, wenn der Spion den Ort richtig errät?",
                    "faq10": "📢 Wie melde ich Probleme oder gebe Feedback?",
                    "what_is_bot": "AgentX Game Bot ist ein interaktiver Discord-Bot, der für ein unterhaltsames und fesselndes Spiel entwickelt wurde. Die Spieler werden in Detektive und einen Spion aufgeteilt, ohne ihre Identität preiszugeben. Der Spion muss den Ort anhand der von den Detektiven gegebenen Hinweise herausfinden, während er versucht, nicht entdeckt zu werden.",
                    "start_game": "Du kannst ein Spiel starten, indem du den `/host` Befehl gefolgt von der gewünschten Spieleranzahl `(mindestens 5 erforderlich)` verwendest.",
                    "join_game_help": "Sobald das Spiel gestartet ist, können die Spieler dem Spiel beitreten, indem sie auf den 'Spiel beitreten' Button in der Spieleinbettungsnachricht klicken. Das Spiel kann beginnen, wenn die erforderliche Anzahl an Spielern beigetreten ist.",
                    "during_game": "Nachdem die Rollen zugewiesen wurden, beginnen die Detektive, sich gegenseitig über gemeinsame Punkte des geheimen Ortes zu befragen. Der Spion muss sich in das Gespräch einfügen und versuchen, den Ort anhand der Hinweise der Detektive zu erraten.",
                    "roles": "**🕵️ AgentX**: AgentX muss den geheimen Ort anhand der von den Detektiven gegebenen Hinweise herausfinden.\n**🔍 Detektiv**: Die Detektive müssen den Spion identifizieren, indem sie die Fragen und Antworten des Spions analysieren.",
                    "how_to_play_part1": "1. Nachdem ein Spiel gestartet wurde, können die Spieler dem Spiel beitreten, indem sie auf den 'Spiel beitreten' Button in der Spieleinbettungsnachricht klicken.\n2. Das Spiel kann beginnen, wenn die erforderliche Anzahl an Spielern beigetreten ist.",
                    "how_to_play_part2": "1. Jeder Spieler erhält eine Rolle (Spion oder Detektiv).\n2. Die Detektive werden ihre Hinweise diskutieren, während der Spion versucht, sich einzufügen und den Ort zu erraten.\n3. Die Spieler werden versuchen, den Spion durch das Gespräch zu identifizieren.",
                    "how_to_vote": "1. Wenn du zum Abstimmen aufgefordert wirst, klicken die Spieler auf den Button mit dem Namen der Person, die sie für den Spion halten.\n2. Jeder Spieler kann nur einmal abstimmen und nicht für sich selbst stimmen.",
                    "spy_guess_correct": "Wenn der Spion den Ort richtig errät, gewinnt er das Spiel. Wenn die Detektive den Spion erfolgreich entlarven, bevor er den Ort errät, gewinnen die Detektive.",
                    "report_issues": "Wenn Sie Probleme haben, verwenden Sie `/report`. Haben Sie Vorschläge zur Verbesserung des Bots? Treten Sie unserem Support-Server bei! [Support-Server](https://discord.gg/6fMyHbsDWS)"

                }
            }
        }

    def set_language(self, lang_code):
        if lang_code in self.languages:
            self.current_language = lang_code
            return f"Language set to {lang_code}"
        else:
            return "Language not available."
        
    def get_translation(self, lang_code, *keys):
        translation = self.languages.get(lang_code, {})
        for key in keys:
            translation = translation.get(key, "Translation not found.")
            if translation == "Translation not found.":
                break
        return translation
    